---
  
- include_tasks: facts.yml


- name: set asg first node as the rally point server
  set_fact:
    rally_point_server: "{{ rally_instances[0].private_ip_address }}"
  tags:
    - install

- name: initiate is_rally_point bool
  set_fact:
    is_rally_point: "{{ rally_point_server == ansible_ec2_local_ipv4 }}"
  tags:
    - install

- name: init swam
  shell: docker swarm init
  when: is_rally_point is defined and is_rally_point == true
  tags:
    - install

- name: init swam
  shell: docker swarm join-token -q worker
  when: is_rally_point is defined and is_rally_point == true
  register: swarm_token
  tags:
    - install

- name: install openfass
  shell: git clone https://github.com/openfaas/faas && cd faas && ./deploy_stack.sh --no-auth
  when: is_rally_point is defined and is_rally_point == true
  tags:
    - install    

- name: sleep for 60 seconds
  wait_for:
    timeout: 60

- name: Create key/value pair in aws parameter store
  aws_ssm_parameter_store:
    name: "swarm_token"
    description: "Swarm token"
    value: "{{swarm_token.stdout}}"
  when: is_rally_point is defined and is_rally_point == true

- name: lookup a swam-tokent in ssm
  set_fact:
    ssm_token: "{{ lookup('aws_ssm', 'swarm_token', region='eu-west-1') }}"
  ignore_errors: true
  when: is_rally_point is defined and is_rally_point == false

- name: join as a manager
  shell: docker swarm join --token {{ssm_token}} {{rally_point_server}}:2377 
  when: is_rally_point is defined and is_rally_point == false
  retries: 3
  delay: 20
  tags:
    - install


# - name: lookup ssm parameter store in the current region
#   debug: msg="{{temp_secret}}"
#   changed_when: true   